services:
  db:
    image: mysql:8.0 
    restart: always
    ports:
      - "127.0.0.1:${EXTERNAL_DB_PORT:-3306}:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    # (if want to have GUI tools)
    # ports:
    #   - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DB_NAME: app_db                 # ← from .env
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "${EXTERNAL_WEB_PORT:-3000}:3000"
    command: sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 3000"
    stdin_open: true
    tty: true

volumes:
  mysql_data:
  redis_data:
  